version: "3.8"

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  api:
    build: .
    container_name: judge0_api
    ports:
      - "2358:2358"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    <<: *default-logging
    restart: always
    command: ["sh", "./run"]

  db:
    image: postgres:16.2
    container_name: judge0_db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    container_name: judge0_redis
    command: [
      "bash", "-c",
      "docker-entrypoint.sh --appendonly no --requirepass \"$${REDIS_PASSWORD}\""
    ]
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    <<: *default-logging
    restart: always

volumes:
  data:
