#!/bin/sh
set -e

# Move to app directory
cd /app

# Start background workers (like Sidekiq)
bundle exec sidekiq -d -L log/sidekiq.log

# Start Rails server (Judge0-compatible API)
bundle exec rails s -p 2358 -b 0.0.0.0
